Enable HTTP trailer support
hhxsv5/laravel-s pull request #313
Opened 2020-11-09 04:15 UTC by filakhtov

Hey guys!

Currently playing with Laravel and Swoole and noticed that there is no support for HTTP Trailers.

Swoole supports trailer response headers, but Laravel does not (same as almost all other PHP frameworks). This presents a challenge, where we either need to extend Laravel's (Symfony's to be precise) HTTP response object to include trailers support or take a different strategy.

In this PR, the proposal is to take a different approach, i.e. rely on the `trailer` header to specify the list of all the headers that should be converted into trailing. Similar approach has been taken for [RoadRunner application server](https://github.com/spiral/roadrunner/blob/fea88ad23d8686ec6ddbeb48f5cfc7b2640c036e/service/http/response.go#L89-L107) and worked well, so the hope is that this is a reasonable solution for LaravelS as well. It is backwards compatible with Laravel's response and supports a missing feature properly.

Open to any feedback and suggestions! Thanks in advance.

2020-11-09 08:08 UTC, hhxsv5 requested changes
Thanks for your contribution. 
If it is compatible with PHP 5.x, so much better

2020-11-09 08:08 UTC, hhxsv5 commented on src/Swoole/Response.php
> +        $trailers = $headers["trailer"] ?? [];
Same as above

2020-11-09 08:08 UTC, hhxsv5 commented on src/Swoole/Response.php
> +        $trailers = $headers["trailer"] ?? [];
Same as above

2020-11-09 23:29 UTC, filakhtov commented
Hey @hhxsv5, thanks a lot for the review and your feedback. I have made a requested changes and it is ready for another round, whenever you get a chance 🙏 

I have a quick question for you as well that I am curious about: what is the motivation to keep the compatibility with PHP <7.2? According to the [supported versions page](https://www.php.net/supported-versions.php) from the official PHP website, everything older than 7.2 is EOL and there are no active support or security patches, and even 7.2 is going to EOL in 20 days.

2020-11-10 03:27 UTC, hhxsv5 commented
> Hey @hhxsv5, thanks a lot for the review and your feedback. I have made a requested changes and it is ready for another round, whenever you get a chance 🙏
> 
> I have a quick question for you as well that I am curious about: what is the motivation to keep the compatibility with PHP <7.2? According to the [supported versions page](https://www.php.net/supported-versions.php) from the official PHP website, everything older than 7.2 is EOL and there are no active support or security patches, and even 7.2 is going to EOL in 20 days.

Just to make Swoole available for more old projects 😁.

2020-11-10 03:27 UTC, merged